language: bash

addons:
  apt:
    sources:
    - debian-sid

before_install:
  - sudo apt-get install -y cabal-install shunit2
  - cabal update
  - cabal install shellcheck

script:
  - bash -c 'cd test && ./test_functions.sh'
  - bash -c 'shellcheck -x pieman.sh'
